### PR TITLE
New Flag Editor, and other fixes

### PR DESCRIPTION
**Pull request by CloneTrooper1019**

### CODE REVIEW

**Comment by MaximumADHD** [comment]
This isn't where it began, there was a previous iteration that existed prior for a few years. It just required a more barbaric brute-forced technique.

What do you mean by "fast flag codes"?

**Comment by MaximumADHD** [comment]
There are no other applicable cases where Roblox defines FFlags outside of C++ and Luau.

**Comment by meow8283** [comment]
i see , theres more fast flags lines too ? 
as i see theres too many but i dont think is enough for fflags creators like me , is not a offense but i think is not enough .

**Comment by MaximumADHD** [comment]
FFlags are authored, controlled, and primarily only intended to be used by engineers who work at Roblox. I don’t know where you’re getting this nonsense from but it’s all wrong,

**Comment by meow8283** [comment]
sounds weird, but i see it on a info page about how fflags works, i trough it was made by the bloxstrap dev / team, i have not evidence but i can maybe find the page once agian.

( thanks for answear all my questions, im glad to know more about fflags )

**Pull request merged**
